title: Spearheadmorrow Projects
email: spearheadmorrow@gmail.com

description: "Modern software projects for the recovery community, off- and on-line."

# Use GitHub Pages defaults where possible
markdown: kramdown
